name: Wildfire
favicon: null
layout_spectrum: 0.7892456869594753
typography_spectrum: 0.3309317964594811
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf5f7'
    - '#cddfdf'
    - '#1e4640'
    - '#2c6254'
    - '#6b9c89'
  brandStrength: 0.5
  lightness: 0.6850285744294524
  saturation: 0.2369916515890509
  rhythmicContrast: 0.5
purpose: []
