name: Wildfire
favicon: null
layout_spectrum: 0.11603
typography_spectrum: 0.84512
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebf5f7'
    - '#cddfdf'
    - '#1e4640'
    - '#2c6254'
    - '#6b9c89'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
