name: Wildfire
favicon: null
layout_spectrum: 0.60806
typography_spectrum: 0.92237
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#636053'
    - '#a2dd00'
    - '#8c9b81'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
